# Generated by Django 5.2.8 on 2025-11-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('Round', 'Round'), ('Princess', 'Princess'), ('Cushion', 'Cushion'), ('Oval', 'Oval'), ('Emerald', 'Emerald'), ('Pear', 'Pear'), ('Asscher', 'Asscher'), ('Heart', 'Heart'), ('Radiant', 'Radiant'), ('Marquise', 'Marquise')], max_length=50)),
                ('carat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cut', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=50)),
                ('color', models.CharField(choices=[('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1)),
                ('clarity', models.CharField(choices=[('FL', 'Flawless'), ('IF', 'Internally Flawless'), ('VVS1', 'Very, Very Slightly Included 1'), ('VVS2', 'Very, Very Slightly Included 2'), ('VS1', 'Very Slightly Included 1'), ('VS2', 'Very Slightly Included 2'), ('SI1', 'Slightly Included 1'), ('SI2', 'Slightly Included 2'), ('I1', 'Included 1'), ('I2', 'Included 2'), ('I3', 'Included 3')], max_length=5)),
                ('certificate_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JewelryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metal_type', models.CharField(choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Silver', 'Silver')], max_length=50)),
                ('metal_purity', models.CharField(choices=[('14k', '14k'), ('18k', '18k'), ('22k', '22k'), ('24k', '24k')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category')),
                ('diamonds', models.ManyToManyField(blank=True, to='api.diamond')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.jewelryproduct')),
            ],
        ),
    ]
