# Generated by Django 5.2.8 on 2025-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Precious', 'Precious'), ('Semi-Precious', 'Semi-Precious'), ('Synthetic', 'Synthetic')], max_length=50)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(choices=[('Round', 'Round'), ('Princess', 'Princess'), ('Cushion', 'Cushion'), ('Oval', 'Oval'), ('Emerald', 'Emerald'), ('Pear', 'Pear'), ('Asscher', 'Asscher'), ('Heart', 'Heart'), ('Radiant', 'Radiant'), ('Marquise', 'Marquise')], max_length=50)),
                ('carat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=50)),
                ('clarity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='gemstones',
            field=models.ManyToManyField(blank=True, to='api.gemstone'),
        ),
    ]
