export const GOLD_RATE_API = "https://www.goldapi.io/api/XAU/INR";
export const GOLD_RATE_API_TOKEN = "goldapi-3v4m1smawvuhj2-io";

export const GOLD_CARAT_HALLMARK_MAPPING = {
  "24K": "999",
  "22K": "916",
  "21K": "875",
  "20K": "833",
  "18K": "750",
  "16K": "666",
  "14K": "583",
  "10K": "417",
};

export const JEWELLERY_CATEGORIES = {
  RINGS: [
    "Solitaire Rings",
    "Engagement Rings",
    "Love Rings",
    "Halo Rings",
    "Eternity Rings",
    "Bands",
    "Regular wear Rings",
    "Cocktail Rings",
    "Stackable Rings",
    "Couple Rings",
    "Men's Rings",
  ],
  NECKLACES: [
    "Solitaire Necklaces",
    "Unique Necklaces",
    "Tennis Necklaces",
    "Choker Necklaces",
    "Delicate Necklaces",
    "Legacy Necklaces",
    "Pendant Necklaces",
    "V-Shaped Necklaces",
  ],
  EARRINGS: [
    "Stud Earrings",
    "Hoop Earrings",
    "Dangle Earrings",
    "Drop Earrings",
    "Huggie Earrings",
    "Jhumka Earrings",
    "Cluster Earrings",
    "Teardrop Earrings",
  ],
  MANGALSUTRA: [
    "Traditional Mangalsutra",
    "Contemporary Mangalsutra",
    "Diamond Mangalsutra",
    "Lightweight Mangalsutra",
    "Customizable Mangalsutra",
  ],
  PENDANTS: [
    "Solitaire Pendants",
    "Heart Pendants",
    "Initial Pendants",
    "Religious Pendants",
    "Geometric Pendants",
    "Vintage Pendants",
    "Minimalist Pendants",
  ],
  BRACELETS: [
    "Tennis Bracelets",
    "Bangle Bracelets",
    "Charm Bracelets",
    "Cuff Bracelets",
    "Chain Bracelets",
    "Diamond Line Bracelets",
    "Adjustable Bracelets",
  ],
  NOSEPINS: [
    "Diamond Nosepins",
    "Gold Nosepins",
    "Minimalist Nosepins",
    "Traditional Nosepins",
    "Stud Nosepins",
    "Hoops Nosepins",
  ],
  BANGLES: [
    "Classic Bangles",
    "Diamond Bangles",
    "Stackable Bangles",
    "Hinged Bangles",
    "Open Bangles",
    "Filigree Bangles",
    "Bridal Bangles",
  ],
};
