export const GOLD_RATE_API = "https://www.goldapi.io/api/XAU/INR";
export const GOLD_RATE_API_TOKEN = "goldapi-3v4m1smawvuhj2-io";

export const GOLD_CARAT_HALLMARK_MAPPING = {
  "24K": "999",
  "22K": "916",
  "21K": "875",
  "20K": "833",
  "18K": "750",
  "16K": "666",
  "14K": "583",
  "10K": "417",
};

export const JEWELLERY_CATEGORIES = {
  RINGS: [
    "All Rings",
    "Solitaire Rings",
    "Engagement Rings",
    "Love Rings",
    "Halo Rings",
    "Eternity Rings",
    "Bands",
    "Regular wear Rings",
    "Cocktail Rings",
    "Stackable Rings",
    "Couple Rings",
    "Men's Rings",
  ],
  NECKLACES: [
    "All Necklaces",
    "Solitaire Necklaces",
    "Unique Necklaces",
    "Tennis Necklaces",
    "Choker Necklaces",
    "Delicate Necklaces",
    "Legacy Necklaces",
    "Pendant Necklaces",
    "V-Shaped Necklaces",
  ],
  EARRINGS: [
    "All Earrings",
    "Stud Earrings",
    "Hoop Earrings",
    "Dangle Earrings",
    "Drop Earrings",
    "Huggie Earrings",
    "Jhumka Earrings",
    "Cluster Earrings",
    "Teardrop Earrings",
  ],
  MANGALSUTRA: [
    "All Mangalsutra",
    "Traditional Mangalsutra",
    "Contemporary Mangalsutra",
    "Diamond Mangalsutra",
    "Lightweight Mangalsutra",
    "Customizable Mangalsutra",
  ],
  PENDANTS: [
    "All Pendants",
    "Solitaire Pendants",
    "Heart Pendants",
    "Initial Pendants",
    "Religious Pendants",
    "Geometric Pendants",
    "Vintage Pendants",
    "Minimalist Pendants",
  ],
  BRACELETS: [
    "All Bracelets",
    "Tennis Bracelets",
    "Bangle Bracelets",
    "Charm Bracelets",
    "Cuff Bracelets",
    "Chain Bracelets",
    "Diamond Line Bracelets",
    "Adjustable Bracelets",
  ],
  NOSEPINS: [
    "All Nosepins",
    "Diamond Nosepins",
    "Gold Nosepins",
    "Minimalist Nosepins",
    "Traditional Nosepins",
    "Stud Nosepins",
    "Hoops Nosepins",
  ],
  BANGLES: [
    "All Bangles",
    "Classic Bangles",
    "Diamond Bangles",
    "Stackable Bangles",
    "Hinged Bangles",
    "Open Bangles",
    "Filigree Bangles",
    "Bridal Bangles",
  ],
};


export const JEWELLERY_SAMPLE_DATA = [
  {
    id: "prod_001",
    name: "Classic Solitaire",
    category: "Rings", // Can also be "Necklaces", "Earrings", etc.
    subcategory: "Solitaire Rings",
    price: 1200,
    discountPrice: 999, // Optional
    material: "18K White Gold",
    diamond: {
      carat: 0.5,
      cut: "Excellent",
      color: "D",
      clarity: "VS1",
    },
    isReadyToShip: true,
    isBestSeller: true,
  },
  {
    id: "prod_002",
    name: "Eternity Halo",
    category: "Rings",
    subcategory: "Halo Rings",
    price: 2500,
    material: "14K Rose Gold",
    diamond: {
      carat: 0.75,
      cut: "Very Good",
      color: "F",
      clarity: "SI1",
    },
    isNewArrival: true,
  },
  {
    id: "prod_003",
    name: "Tennis Bracelet",
    category: "Bracelets",
    subcategory: "Tennis Bracelets",
    price: 3200,
    material: "Platinum",
    diamond: {
      carat: 2.0, // Total carat weight
      cut: "Ideal",
      color: "G",
      clarity: "VS2",
    },
    isCustomizable: true,
  },
  {
    id: "prod_004",
    name: "Delicate Pendant",
    category: "Pendants",
    subcategory: "Solitaire Pendants",
    price: 800,
    material: "18K Yellow Gold",
    diamond: {
      carat: 0.25,
      cut: "Good",
      color: "H",
      clarity: "SI2",
    },
    isReadyToShip: true,
  },
  {
    id: "prod_005",
    name: "Vintage Choker",
    category: "Necklaces",
    subcategory: "Choker Necklaces",
    price: 1800,
    material: "18K White Gold",
    diamond: {
      carat: 1.2,
      cut: "Excellent",
      color: "E",
      clarity: "VVS2",
    },
    isLimitedEdition: true,
  },
  {
    id: "prod_006",
    name: "Huggie Hoops",
    category: "Earrings",
    subcategory: "Hoop Earrings",
    price: 650,
    material: "14K Yellow Gold",
    diamond: {
      carat: 0.1, // Per earring
      cut: "Very Good",
      color: "I",
      clarity: "SI1",
    },
    isBestSeller: true,
  },
  {
    id: "prod_007",
    name: "Bridal Mangalsutra",
    category: "Mangalsutra",
    subcategory: "Diamond Mangalsutra",
    price: 1500,
    material: "22K Gold",
    diamond: {
      carat: 0.5,
      cut: "Good",
      color: "G",
      clarity: "SI2",
    },
    isBridalCollection: true,
  },
];